import { library } from '@fortawesome/fontawesome-svg-core';
import { 
  faTableTennisPaddleBall, 
  faBars, 
  faChevronDown, 
  faPlayCircle,
  faCheck,
  faTimes,
  faArrowRight,
  faBookOpen,
  faGraduationCap,
  faLightbulb,
  faInfoCircle,
  faExclamationTriangle,
  faQuestionCircle,
  faTrophy,
  faHandPointRight,
  faVideo,
  faArrowLeft,
  faListCheck,
  faBookBookmark,
  faClipboardCheck,
  faChevronUp,
  faImages,
  faClock,
  faRedo
} from '@fortawesome/free-solid-svg-icons';

// Add icons to the library
library.add(
  faTableTennisPaddleBall,
  faBars,
  faChevronDown,
  faPlayCircle,
  faCheck,
  faTimes,
  faArrowRight,
  faBookOpen,
  faGraduationCap,
  faLightbulb,
  faInfoCircle,
  faExclamationTriangle,
  faQuestionCircle,
  faTrophy,
  faHandPointRight,
  faVideo,
  faArrowLeft,
  faListCheck,
  faBookBookmark,
  faClipboardCheck,
  faChevronUp,
  faImages,
  faClock,
  faRedo
);
